runtime: python39

env_variables:
  DB_HOST: "34.121.60.244"
  DB_USER: "kshitij"
  DB_PASSWORD: "Kshitij_17"
  DB_NAME: "stocks"

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html

  - url: /static/.*
    static_dir: frontend/build/static

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10 